version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
#     schedule:
#       interval: "daily"
#       time: "21:00"
    open-pull-requests-limit: 10
    # Increase the version requirements
    # only when required
    versioning-strategy: increase-if-necessary
    #reviewers:
    #  - "hantsy"
    #assignees:
    #  - "hantsy"
    labels:
      - "dependencies"
      - "npm"
